hf_dataset_name: locuslab/TOFU
hf_dataset_split: full
is_wtm: false
forget_ratio: 0.1
forget_calibration_ratio: 0.06
forget_dup_ratio: 0.1
train_dup_data_dir: ~/maplecg_nfs_public/datasets/TOFU/tofu_paraphrased_train_dataset