hf_dataset_name: locuslab/TOFU
dataset_dir: ~/maplecg_nfs_public/waterfall/tofu/0.05_split/
is_wtm: true
forget_ratio: 0.05
forget_calibration_ratio: 0.05
forget_dup_ratio: 0.05
train_dup_data_dir: ~/maplecg_nfs_public/waterfall/tofu/id0/