hf_dataset_name: locuslab/TOFU
dataset_dir: ~/maplecg_nfs_public/waterfall/tofu/0.01_split/
is_wtm: true
forget_ratio: 0.01
forget_calibration_ratio: 0.01
forget_dup_ratio: 0.01
train_dup_data_dir: ~/maplecg_nfs_public/datasets/TOFU/watermarked_tofu_paraphrased_train_dataset/id_0.pkl      # duplicated data that has been watermarked differently